# Week 03: NumPy 기초 실습

이번 실습은 NumPy 입문 단계에서 자주 배우는 순서대로 구성되어 있다. 셀을 위에서부터 순서대로 실행하면서 배열 생성, 정규분포 난수, 속성 확인, 인덱싱, 슬라이싱, 연산, 집계, reshape를 누적형으로 익힌다.

In [ ]:
import numpy as np
import sys
import time

## 1. `np.array()`로 배열 만들기

파이썬 리스트를 NumPy 배열로 바꾸는 가장 기본적인 방법이다.

In [61]:
arr = np.array([1, 2, 3, 4, 5])

print("arr =", arr)
print("type(arr) =", type(arr))

arr = [1 2 3 4 5]
type(arr) = <class 'numpy.ndarray'>


## 2. 기본 배열 생성 메서드

`zeros`, `ones`, `empty`, `full`, `arange`, `uniform`은 NumPy 입문에서 자주 사용하는 생성 메서드들이다.

In [64]:
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((2, 3))
empty_arr = np.empty((2, 3))
full_arr = np.full((2, 3), 7)
range_arr = np.arange(1, 7)

np.random.seed(42)
uniform_arr = np.random.uniform(0, 1, 5)

print("zeros_arr =\n", zeros_arr)
print("ones_arr =\n", ones_arr)
print("empty_arr =\n", empty_arr)
print("full_arr =\n", full_arr)
print("range_arr =", range_arr)
print("uniform_arr =", uniform_arr)

zeros_arr =
 [[0. 0. 0.]
 [0. 0. 0.]]
ones_arr =
 [[1. 1. 1.]
 [1. 1. 1.]]
empty_arr =
 [[0. 0. 0.]
 [0. 0. 0.]]
full_arr =
 [[7 7 7]
 [7 7 7]]
range_arr = [1 2 3 4 5 6]
uniform_arr = [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


## 2-1. 정규분포 난수 생성

`np.random.normal()`은 평균과 표준편차를 기준으로 정규분포를 따르는 난수를 만든다. `uniform`과 비교해 보면 분포의 차이를 이해하기 쉽다.

In [67]:
np.random.seed(42)
normal_arr = np.random.normal(loc=50, scale=10, size=5)
normal_arr_large = np.random.normal(loc=50, scale=10, size=1000)

print("normal_arr =", np.round(normal_arr, 2))
print("normal_arr_large 평균 =", round(np.mean(normal_arr_large), 2))
print("normal_arr_large 표준편차 =", round(np.std(normal_arr_large), 2))

normal_arr = [54.97 48.62 56.48 65.23 47.66]
normal_arr_large 평균 = 50.19
normal_arr_large 표준편차 = 9.79


## 3. 배열의 기본 속성 확인

`shape`, `ndim`, `size`, `dtype`는 배열을 이해할 때 가장 먼저 확인하는 속성이다.

In [70]:
matrix = range_arr.reshape(2, 3)

print("arr =", arr)
print("arr.shape =", arr.shape)
print("arr.ndim =", arr.ndim)
print("arr.size =", arr.size)
print("arr.dtype =", arr.dtype)

print()
print("matrix =\n", matrix)
print("matrix.shape =", matrix.shape)
print("matrix.ndim =", matrix.ndim)
print("matrix.size =", matrix.size)
print("matrix.dtype =", matrix.dtype)
print("matrix.T =\n", matrix.T)

arr = [1 2 3 4 5]
arr.shape = (5,)
arr.ndim = 1
arr.size = 5
arr.dtype = int64

matrix =
 [[1 2 3]
 [4 5 6]]
matrix.shape = (2, 3)
matrix.ndim = 2
matrix.size = 6
matrix.dtype = int64
matrix.T =
 [[1 4]
 [2 5]
 [3 6]]


## 4. 1차원 배열 인덱싱과 슬라이싱

앞에서 만든 `arr`를 이용해 값 선택과 구간 선택을 실습한다.

In [73]:
print("arr =", arr)
print("arr[0] =", arr[0])
print("arr[2] =", arr[2])
print("arr[-1] =", arr[-1])

print("arr[1:4] =", arr[1:4])
print("arr[:3] =", arr[:3])
print("arr[2:] =", arr[2:])
print("arr[::2] =", arr[::2])

arr = [1 2 3 4 5]
arr[0] = 1
arr[2] = 3
arr[-1] = 5
arr[1:4] = [2 3 4]
arr[:3] = [1 2 3]
arr[2:] = [3 4 5]
arr[::2] = [1 3 5]


## 5. 2차원 배열 인덱싱과 슬라이싱

이번에는 `matrix`를 이용해 행과 열을 선택한다.

In [76]:
print("matrix =\n", matrix)
print("matrix[0, 0] =", matrix[0, 0])
print("matrix[1, 2] =", matrix[1, 2])
print("matrix[0, :] =", matrix[0, :])
print("matrix[:, 1] =", matrix[:, 1])
print("matrix[:, :2] =\n", matrix[:, :2])

matrix =
 [[1 2 3]
 [4 5 6]]
matrix[0, 0] = 1
matrix[1, 2] = 6
matrix[0, :] = [1 2 3]
matrix[:, 1] = [2 5]
matrix[:, :2] =
 [[1 2]
 [4 5]]


## 6. 배열 연산과 브로드캐스팅

NumPy는 배열 전체에 연산을 한 번에 적용할 수 있다.

In [79]:
arr_plus_ten = arr + 10
arr_times_two = arr * 2
arr_plus_uniform = arr + uniform_arr
ones_vector = np.ones(5)

print("arr + 10 =", arr_plus_ten)
print("arr * 2 =", arr_times_two)
print("arr + uniform_arr =", arr_plus_uniform)
print("arr + ones_vector =", arr + ones_vector)

arr + 10 = [11 12 13 14 15]
arr * 2 = [ 2  4  6  8 10]
arr + uniform_arr = [1.37454012 2.95071431 3.73199394 4.59865848 5.15601864]
arr + ones_vector = [2. 3. 4. 5. 6.]


## 7. 자주 쓰는 집계 함수

`sum`, `mean`, `max`, `min`은 배열 데이터를 요약할 때 자주 사용한다.

In [82]:
print("arr 합계 =", np.sum(arr))
print("arr 평균 =", np.mean(arr))
print("arr 최댓값 =", np.max(arr))
print("arr 최솟값 =", np.min(arr))

print("matrix 행별 합계 =", np.sum(matrix, axis=1))
print("matrix 열별 합계 =", np.sum(matrix, axis=0))
print("normal_arr 평균 =", np.mean(normal_arr))

arr 합계 = 15
arr 평균 = 3.0
arr 최댓값 = 5
arr 최솟값 = 1
matrix 행별 합계 = [ 6 15]
matrix 열별 합계 = [5 7 9]
normal_arr 평균 = 54.59002974325087


## 8. 배열 모양 바꾸기

`reshape()`는 원소 수를 유지한 채 배열의 구조만 바꾼다.

In [85]:
reshaped_3x2 = range_arr.reshape(3, 2)
reshaped_1x6 = range_arr.reshape(1, 6)

print("range_arr =", range_arr)
print("reshaped_3x2 =\n", reshaped_3x2)
print("reshaped_1x6 =\n", reshaped_1x6)

range_arr = [1 2 3 4 5 6]
reshaped_3x2 =
 [[1 2]
 [3 4]
 [5 6]]
reshaped_1x6 =
 [[1 2 3 4 5 6]]


## 9. 미니 실습: 점수 배열 다루기

지금까지 배운 내용을 간단한 점수 데이터에 적용해 본다.

In [88]:
scores = np.array([[90, 80, 100], [70, 85, 95]])

print("scores =\n", scores)
print("첫 번째 학생 점수 =", scores[0, :])
print("두 번째 과목 점수 =", scores[:, 1])
print("학생별 총점 =", np.sum(scores, axis=1))
print("과목별 평균 =", np.mean(scores, axis=0))

scores =
 [[ 90  80 100]
 [ 70  85  95]]
첫 번째 학생 점수 = [ 90  80 100]
두 번째 과목 점수 = [80 85]
학생별 총점 = [270 250]
과목별 평균 = [80.  82.5 97.5]


## 10. 리스트와 NumPy 배열의 메모리 비교

같은 수치 데이터를 저장하더라도 리스트와 NumPy 배열은 메모리 사용 방식이 다르다.

In [91]:
list_data = [1, 2, 3, 4, 5]
array_data = np.array([1, 2, 3, 4, 5])

print("List 메모리 크기:", sys.getsizeof(list_data) * len(list_data))
print("NumPy 배열 메모리 크기:", array_data.nbytes)

List 메모리 크기: 520
NumPy 배열 메모리 크기: 40


## 11. 리스트와 NumPy 배열의 연산 속도 비교

큰 데이터에서는 리스트보다 NumPy 배열 연산이 더 빠른 경우가 많다.

In [94]:
size = 10**6

list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result_list = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("리스트 연산 시간:", end - start)

arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result_array = arr1 + arr2
end = time.time()
print("NumPy 연산 시간:", end - start)

리스트 연산 시간: 0.04161691665649414
NumPy 연산 시간: 0.0018379688262939453


## 12. 고급 연산 실습

NumPy 배열 객체에서는 평균, 합계, 표준편차, 내적 같은 연산을 바로 수행할 수 있다.

In [96]:
advanced_arr = np.array([1, 2, 3, 4, 5])

print("advanced_arr =", advanced_arr)
print(np.mean(advanced_arr))  # 평균
print(np.sum(advanced_arr))   # 합계
print(np.std(advanced_arr))   # 표준편차
print(np.dot(advanced_arr, advanced_arr))  # 내적 (dot product)

advanced_arr = [1 2 3 4 5]
3.0
15
1.4142135623730951
55


## 13. 벡터 기초 실습

NumPy의 1차원 배열은 벡터처럼 다룰 수 있다. 아래에서는 코드 셀과 설명 셀을 번갈아 보면서 벡터 연산을 따라간다.

In [ ]:
b = np.array([1, 3])
c = np.array([4, 2])

print("b =", b)
print("c =", c)
print("b.dot(c) =", b.dot(c))

설명: `b.dot(c)`는 벡터 내적입니다. `[1, 3]`과 `[4, 2]`의 내적은 `1*4 + 3*2 = 10`입니다.

In [106]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

print("vector_a =", vector_a)
print("vector_b =", vector_b)
print("벡터 덧셈 =", vector_a + vector_b)
print("벡터 뺄셈 =", vector_b - vector_a)

vector_a = [1 2 3]
vector_b = [4 5 6]
벡터 덧셈 = [5 7 9]
벡터 뺄셈 = [3 3 3]


설명: 벡터 덧셈과 뺄셈은 같은 위치의 원소끼리 계산합니다.

In [108]:
print("스칼라 곱 =", 3 * vector_a)
print("벡터 내적 =", np.dot(vector_a, vector_b))
print("vector_a 크기 =", np.linalg.norm(vector_a))

스칼라 곱 = [3 6 9]
벡터 내적 = 32
vector_a 크기 = 3.7416573867739413


설명: 스칼라 곱은 모든 원소에 같은 수를 곱하는 것이고, `np.linalg.norm()`은 벡터의 크기(길이)를 구합니다.

## 14. 직접 해보기

1. `np.full((2, 2), 9)` 배열을 만들어 보자.
2. `np.arange(1, 10)` 배열을 만들어 보자.
3. `arr`에서 슬라이싱으로 `[2 3 4]`를 꺼내 보자.
4. `matrix`에서 첫 번째 열만 꺼내 보자.
5. `range_arr`를 `2 x 3`으로 바꿔 보자.
6. `scores`의 학생별 평균을 구해 보자.
7. `np.random.normal(loc=100, scale=15, size=5)`로 정규분포 난수를 만들어 보자.
8. `normal_arr_large`의 평균과 표준편차를 구해 보자.
9. `np.array([1, 2, 3, 4, 5])`의 표준편차를 구해 보자.
10. `np.array([1, 2, 3, 4, 5])`와 자기 자신의 내적을 구해 보자.
11. `b = np.array([1, 3])`, `c = np.array([4, 2])`일 때 `b.dot(c)`를 구해 보자.
12. `vector_a + vector_b`를 다시 구해 보자.
13. `vector_a`의 크기(norm)를 구해 보자.